package gui;

import conect.Conexao;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author Santiago
 */
public class Formulario extends javax.swing.JFrame {
    Conexao con_base;
    int navega = 0;
    
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        
        con_base = new Conexao();
        con_base.conecta();
        setFormatNumber("##/##/####", tf_dt_nac, "1234567890");
        setFormatNumber("(##) #####-####", tf_Telefone, "1234567890");
        setFormatNumber("##.###.###-#", tf_rg, "1234567890");
        setFormatNumber("###.###.###-##", tf_cpf, "1234567890");
        
        con_base.executa("select * from Clientes");
        try 
        {
            
            con_base.resultset.first();
            tf_Codigo.setText(con_base.resultset.getString("Código"));
            tf_Autor.setText(con_base.resultset.getString("Autor"));
            tf_Reu.setText(con_base.resultset.getString("Réu"));
            tf_Forum.setText(con_base.resultset.getString("Fórum"));
            tf_Acao.setText(con_base.resultset.getString("Ação"));
            tf_Processo.setText(con_base.resultset.getString("Processo"));
            tf_Telefone.setText(con_base.resultset.getString("Telefone"));
            tf_Andamento.setText(con_base.resultset.getString("Andamento"));
            tf_Audiencia.setText(con_base.resultset.getString("Audiencia"));
            tf_Tarefas.setText(con_base.resultset.getString("Tarefas"));
            tf_Vara.setText(con_base.resultset.getString("Vara"));
            tf_matricula.setText(con_base.resultset.getString("matricula"));
            tf_rg.setText(con_base.resultset.getString("rg"));
            tf_cpf.setText(con_base.resultset.getString("cpf"));
            tf_endereco.setText(con_base.resultset.getString("endereco"));
            tf_dt_nac.setText(con_base.resultset.getString("data_nasc"));
            tf_local_prisao.setText(con_base.resultset.getString("local_prisao"));
            ckNovo.setSelected(con_base.resultset.getBoolean("novo"));
                
        }
        catch(SQLException erro)
        {
            JOptionPane.showConfirmDialog(null,"Não localizou dados " +erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisar = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tf_Tarefas1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tf_Andamento1 = new javax.swing.JTextArea();
        lb_acao1 = new javax.swing.JLabel();
        btn_Salvar1 = new javax.swing.JButton();
        lb_processo1 = new javax.swing.JLabel();
        lb_audiencia1 = new javax.swing.JLabel();
        btn_excluir1 = new javax.swing.JButton();
        lb_tarefas1 = new javax.swing.JLabel();
        tf_Autor1 = new javax.swing.JTextField();
        tf_Reu1 = new javax.swing.JTextField();
        tf_Forum1 = new javax.swing.JTextField();
        tf_Vara1 = new javax.swing.JTextField();
        tf_Audiencia1 = new javax.swing.JTextField();
        lb_autor1 = new javax.swing.JLabel();
        lb_reu1 = new javax.swing.JLabel();
        lb_forum1 = new javax.swing.JLabel();
        lb_vara1 = new javax.swing.JLabel();
        lb_contato1 = new javax.swing.JLabel();
        lb_andamento1 = new javax.swing.JLabel();
        tf_Acao1 = new javax.swing.JTextField();
        tf_Processo1 = new javax.swing.JTextField();
        tf_Codigo1 = new javax.swing.JTextField();
        lb_codigo1 = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        tf_matricula1 = new javax.swing.JTextField();
        lb_contato3 = new javax.swing.JLabel();
        lb_audiencia2 = new javax.swing.JLabel();
        lb_audiencia3 = new javax.swing.JLabel();
        lb_contato4 = new javax.swing.JLabel();
        lb_contato5 = new javax.swing.JLabel();
        tf_endereco1 = new javax.swing.JTextField();
        tf_local_prisao1 = new javax.swing.JTextField();
        lb_audiencia4 = new javax.swing.JLabel();
        ckNovo1 = new javax.swing.JCheckBox();
        tf_cpf1 = new javax.swing.JFormattedTextField();
        tf_dt_nac1 = new javax.swing.JFormattedTextField();
        tf_rg1 = new javax.swing.JFormattedTextField();
        tf_Telefone1 = new javax.swing.JFormattedTextField();
        painelPrincipal = new javax.swing.JPanel();
        lb_codigo = new javax.swing.JLabel();
        lb_autor = new javax.swing.JLabel();
        lb_reu = new javax.swing.JLabel();
        lb_forum = new javax.swing.JLabel();
        lb_vara = new javax.swing.JLabel();
        lb_contato = new javax.swing.JLabel();
        lb_processo = new javax.swing.JLabel();
        tf_Autor = new javax.swing.JTextField();
        tf_Reu = new javax.swing.JTextField();
        tf_Forum = new javax.swing.JTextField();
        tf_Vara = new javax.swing.JTextField();
        tf_Acao = new javax.swing.JTextField();
        tf_Processo = new javax.swing.JTextField();
        tf_Codigo = new javax.swing.JTextField();
        tf_pesquisar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        lb_matricula = new javax.swing.JLabel();
        tf_matricula = new javax.swing.JTextField();
        lb_dt_nasc = new javax.swing.JLabel();
        lb_contato2 = new javax.swing.JLabel();
        lb_acao4 = new javax.swing.JLabel();
        lb_endereco = new javax.swing.JLabel();
        lb_loc_prisao = new javax.swing.JLabel();
        tf_local_prisao = new javax.swing.JTextField();
        lb_acao2 = new javax.swing.JLabel();
        comboPesquisa = new javax.swing.JComboBox();
        ckNovo = new javax.swing.JCheckBox();
        tf_dt_nac = new javax.swing.JFormattedTextField();
        tf_cpf = new javax.swing.JFormattedTextField();
        tf_rg = new javax.swing.JFormattedTextField();
        tf_endereco = new javax.swing.JTextField();
        tf_Telefone = new javax.swing.JFormattedTextField();
        btn_Proximo = new javax.swing.JButton();
        btn_Primeiro = new javax.swing.JButton();
        btn_Anterior = new javax.swing.JButton();
        btn_Ultimo = new javax.swing.JButton();
        btn_Novo = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        lb_endereco1 = new javax.swing.JLabel();
        lb_endereco2 = new javax.swing.JLabel();
        lb_endereco3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tf_Audiencia = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tf_Tarefas = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tf_Andamento = new javax.swing.JTextArea();
        menuPrincipal = new javax.swing.JMenuBar();
        menuBase = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenu();

        tf_Tarefas1.setColumns(20);
        tf_Tarefas1.setRows(5);
        jScrollPane3.setViewportView(tf_Tarefas1);

        tf_Andamento1.setColumns(20);
        tf_Andamento1.setRows(5);
        jScrollPane4.setViewportView(tf_Andamento1);

        lb_acao1.setText("Ação: ");

        btn_Salvar1.setText("Salvar");
        btn_Salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Salvar1ActionPerformed(evt);
            }
        });

        lb_processo1.setText("Processo:");

        lb_audiencia1.setText("Audiência:");

        btn_excluir1.setText("EXCLUIR");
        btn_excluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir1ActionPerformed(evt);
            }
        });

        lb_tarefas1.setText("Tarefas:");

        tf_Autor1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        tf_Reu1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        tf_Forum1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        tf_Vara1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        tf_Audiencia1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_Audiencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_Audiencia1ActionPerformed(evt);
            }
        });

        lb_autor1.setText("Autor:");

        lb_reu1.setText("Reu: ");

        lb_forum1.setText("Fórum:");

        lb_vara1.setText("Vara:");

        lb_contato1.setText("Contato:");

        lb_andamento1.setText("Andamento:");

        tf_Acao1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_Acao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_Acao1ActionPerformed(evt);
            }
        });

        tf_Processo1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_Processo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_Processo1ActionPerformed(evt);
            }
        });

        tf_Codigo1.setText("     ");

        lb_codigo1.setText("Código:");

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        tf_matricula1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_matricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_matricula1ActionPerformed(evt);
            }
        });

        lb_contato3.setText("Matricula:");

        lb_audiencia2.setText("Data de Nasc:");

        lb_audiencia3.setText("CPF:");

        lb_contato4.setText("RG:");

        lb_contato5.setText("Endereço:");

        tf_endereco1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_endereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_endereco1ActionPerformed(evt);
            }
        });

        tf_local_prisao1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_local_prisao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_local_prisao1ActionPerformed(evt);
            }
        });

        lb_audiencia4.setText("Local da Prisão:");

        ckNovo1.setText("Novo Processo");

        javax.swing.GroupLayout pesquisarLayout = new javax.swing.GroupLayout(pesquisar.getContentPane());
        pesquisar.getContentPane().setLayout(pesquisarLayout);
        pesquisarLayout.setHorizontalGroup(
            pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisarLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(btnAnterior)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pesquisarLayout.createSequentialGroup()
                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pesquisarLayout.createSequentialGroup()
                                    .addComponent(lb_forum1)
                                    .addGap(23, 23, 23))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarLayout.createSequentialGroup()
                                    .addComponent(lb_vara1)
                                    .addGap(31, 31, 31)))
                            .addGroup(pesquisarLayout.createSequentialGroup()
                                .addComponent(lb_contato1)
                                .addGap(14, 14, 14)))
                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pesquisarLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pesquisarLayout.createSequentialGroup()
                                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_Forum1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_Vara1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lb_acao1)
                                                .addGroup(pesquisarLayout.createSequentialGroup()
                                                    .addComponent(lb_processo1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(tf_Processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(tf_Acao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pesquisarLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_audiencia2)
                                            .addComponent(lb_audiencia1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_dt_nac1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_Audiencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pesquisarLayout.createSequentialGroup()
                                .addComponent(tf_Telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_tarefas1)
                                .addGap(18, 18, 18)
                                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProximo)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pesquisarLayout.createSequentialGroup()
                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_autor1)
                            .addComponent(lb_reu1)
                            .addComponent(lb_codigo1))
                        .addGap(22, 22, 22)
                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pesquisarLayout.createSequentialGroup()
                                .addComponent(tf_Codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ckNovo1)
                                .addGap(79, 79, 79)
                                .addComponent(btn_Salvar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_excluir1))
                            .addComponent(tf_Reu1)
                            .addComponent(tf_Autor1)))
                    .addGroup(pesquisarLayout.createSequentialGroup()
                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_contato5)
                            .addComponent(lb_contato4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pesquisarLayout.createSequentialGroup()
                                .addComponent(tf_endereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_audiencia4))
                            .addGroup(pesquisarLayout.createSequentialGroup()
                                .addComponent(tf_rg1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_audiencia3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_local_prisao1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(tf_cpf1)))
                    .addGroup(pesquisarLayout.createSequentialGroup()
                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pesquisarLayout.createSequentialGroup()
                                .addComponent(lb_andamento1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pesquisarLayout.createSequentialGroup()
                                .addComponent(lb_contato3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_matricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 426, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pesquisarLayout.setVerticalGroup(
            pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_excluir1)
                        .addComponent(btn_Salvar1)
                        .addComponent(lb_codigo1)
                        .addComponent(tf_Codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ckNovo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_autor1)
                    .addComponent(tf_Autor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_reu1)
                    .addComponent(tf_Reu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_forum1)
                    .addComponent(lb_acao1)
                    .addComponent(tf_Forum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Acao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tf_Processo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_processo1))
                    .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_vara1)
                        .addComponent(tf_Vara1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_contato1)
                    .addComponent(lb_audiencia1)
                    .addComponent(tf_Audiencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_contato3)
                    .addComponent(tf_matricula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_dt_nac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_audiencia2))
                .addGap(14, 14, 14)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_contato4)
                    .addComponent(lb_audiencia3)
                    .addComponent(tf_rg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_contato5)
                    .addComponent(lb_audiencia4)
                    .addComponent(tf_local_prisao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_endereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pesquisarLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_andamento1)
                            .addComponent(lb_tarefas1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnProximo))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_codigo.setText("Código:");

        lb_autor.setText("Autor:");

        lb_reu.setText("Reu: ");

        lb_forum.setText("Fórum:");

        lb_vara.setText("Vara:");

        lb_contato.setText("Contato:");

        lb_processo.setText("Processo:");

        tf_Autor.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        tf_Reu.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        tf_Forum.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        tf_Vara.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        tf_Acao.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_Acao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_AcaoActionPerformed(evt);
            }
        });

        tf_Processo.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_Processo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ProcessoActionPerformed(evt);
            }
        });

        tf_Codigo.setText("     ");

        tf_pesquisar.setText("Pesquisar:");
        tf_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisarActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar por");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lb_matricula.setText("Matricula:");

        tf_matricula.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_matriculaActionPerformed(evt);
            }
        });

        lb_dt_nasc.setText("Data de Nasc:");

        lb_contato2.setText("RG:");

        lb_acao4.setText("CPF:");

        lb_endereco.setText("Endereço:");

        lb_loc_prisao.setText("Local da Prisão:");

        tf_local_prisao.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_local_prisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_local_prisaoActionPerformed(evt);
            }
        });

        lb_acao2.setText("Ação:");

        comboPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Processo", "Autor", "Réu", "Fórum", "Vara", "Contato", "RG", "Endereço", "Ação", "Matricula", "Data de Nascimento", "CPF", "Local da Prisão" }));
        comboPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPesquisaActionPerformed(evt);
            }
        });

        ckNovo.setText("Novo Processo");
        ckNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckNovoActionPerformed(evt);
            }
        });

        tf_dt_nac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dt_nacActionPerformed(evt);
            }
        });

        tf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cpfActionPerformed(evt);
            }
        });

        tf_rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rgActionPerformed(evt);
            }
        });

        tf_endereco.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_enderecoActionPerformed(evt);
            }
        });

        tf_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(painelPrincipalLayout.createSequentialGroup()
                                            .addComponent(lb_forum)
                                            .addGap(31, 31, 31))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                                            .addComponent(lb_vara)
                                            .addGap(39, 39, 39)))
                                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_contato)
                                            .addComponent(lb_contato2))
                                        .addGap(22, 22, 22)))
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_Vara, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(lb_endereco)
                                .addGap(18, 18, 18)
                                .addComponent(tf_endereco)))
                        .addGap(46, 46, 46)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lb_matricula)
                                .addComponent(lb_dt_nasc)
                                .addComponent(lb_acao4)
                                .addComponent(lb_acao2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_loc_prisao))
                        .addGap(119, 119, 119)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_local_prisao, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(tf_dt_nac)
                            .addComponent(tf_matricula)
                            .addComponent(tf_Acao)
                            .addComponent(tf_cpf)))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_processo)
                            .addComponent(lb_autor)
                            .addComponent(lb_reu)
                            .addComponent(lb_codigo))
                        .addGap(18, 18, 18)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Forum, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_Reu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                                .addComponent(tf_Autor, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf_Processo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createSequentialGroup()
                                        .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(tf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_buscar)))
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(comboPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(ckNovo)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_codigo)
                    .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(comboPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Processo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_processo)))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckNovo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_autor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Reu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_reu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_forum)
                    .addComponent(tf_Forum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_acao2)
                    .addComponent(tf_Acao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_matricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_vara)
                        .addComponent(tf_Vara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_matricula)))
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_contato)
                            .addComponent(tf_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_contato2))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_dt_nasc)
                            .addComponent(tf_dt_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_acao4)
                                .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_loc_prisao)
                        .addComponent(tf_local_prisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_endereco)
                        .addComponent(tf_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        btn_Proximo.setText("Próximo");
        btn_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProximoActionPerformed(evt);
            }
        });

        btn_Primeiro.setText("Primeiro");
        btn_Primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrimeiroActionPerformed(evt);
            }
        });

        btn_Anterior.setText("Anterior");
        btn_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnteriorActionPerformed(evt);
            }
        });

        btn_Ultimo.setText("Último");
        btn_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UltimoActionPerformed(evt);
            }
        });

        btn_Novo.setText("Novo");
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_excluir.setText("EXCLUIR");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        lb_endereco1.setText("Audiências:");

        lb_endereco2.setText("Tarefas:");

        lb_endereco3.setText("Andamentos:");

        tf_Audiencia.setColumns(20);
        tf_Audiencia.setRows(5);
        jScrollPane2.setViewportView(tf_Audiencia);

        tf_Tarefas.setColumns(20);
        tf_Tarefas.setRows(5);
        jScrollPane5.setViewportView(tf_Tarefas);

        tf_Andamento.setColumns(20);
        tf_Andamento.setRows(5);
        jScrollPane6.setViewportView(tf_Andamento);

        menuBase.setText("Base");
        menuPrincipal.add(menuBase);

        menuSobre.setText("Sobre");
        menuPrincipal.add(menuSobre);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btn_Primeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Proximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Ultimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Novo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_excluir))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_endereco2)
                                    .addComponent(lb_endereco1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(lb_endereco3))
                                    .addComponent(jScrollPane5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(479, 479, 479)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 128, Short.MAX_VALUE))
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_endereco3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_endereco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_endereco2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Proximo)
                    .addComponent(btn_Primeiro)
                    .addComponent(btn_Anterior)
                    .addComponent(btn_Ultimo)
                    .addComponent(btn_Novo)
                    .addComponent(btn_Salvar)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_AcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_AcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_AcaoActionPerformed

    private void tf_ProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ProcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ProcessoActionPerformed

    private void btn_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProximoActionPerformed
        // TODO add your handling code here:
        proximo();
        
    }//GEN-LAST:event_btn_ProximoActionPerformed

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
        // TODO add your handling code here:
        limpar_Dados();
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnteriorActionPerformed
        // TODO add your handling code here:
        anterior();
    }//GEN-LAST:event_btn_AnteriorActionPerformed

    private void btn_PrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrimeiroActionPerformed
        // TODO add your handling code here:
        try
        {
            con_base.resultset.first();
            mostrar_Dados();
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível ir para o "
                    + "primerio registro "+erro);
        }
    }//GEN-LAST:event_btn_PrimeiroActionPerformed

    private void btn_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UltimoActionPerformed
        // TODO add your handling code here:
        try
        {
            con_base.resultset.last();
            mostrar_Dados();
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível ir para o "
                    + "último registro. "+erro);
        }
        
    }//GEN-LAST:event_btn_UltimoActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        // TODO add your handling code here:
        try
        {
            
            String codigo = tf_Codigo.getText();
            String autor = tf_Autor.getText();
            String reu = tf_Reu.getText();
            String forum = tf_Forum.getText();
            String acao = tf_Acao.getText();
            String processo = tf_Processo.getText();
            String telefone = tf_Telefone.getText();
            String andamento = tf_Andamento.getText();
            String audiencia = tf_Audiencia.getText();
            String tarefas = tf_Tarefas.getText();
            String vara = tf_Vara.getText();
            String rg = tf_rg.getText();
            String cpf = tf_cpf.getText();
            String endereco = tf_endereco.getText();
            String matricula = tf_matricula.getText();
            String dt_nasc = tf_dt_nac.getText();
            String local_prisao = tf_local_prisao.getText();
            boolean novo = ckNovo.isSelected();
            
            if (codigo.isEmpty()){
                if(processo.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "O número do processo está vazio");
                } else {
                
                    //Inserção no Banco de Dados
                    String insertSQL = "Insert into Clientes (Autor, Réu, Fórum,"
                            + "Ação, Vara, Processo, Telefone, Andamento, Audiencia, "
                            + "Tarefas, matricula, data_nasc, rg, cpf, endereco, "
                            + "local_prisao, novo) values ('"+autor+"','"+reu+"',"
                            + "'"+forum+"', '"+acao+"', '"+vara+"', '"+processo+"', '"+telefone+"', "
                            + "'"+andamento+"', '"+audiencia+"', '"+tarefas+"', "
                            + "'"+matricula+"', '"+dt_nasc+"', '"+rg+"', '"+cpf+"', "
                            + "'"+endereco+"', '"+local_prisao+"', '"+novo+"')";

                    con_base.statement.executeUpdate(insertSQL);
                    con_base.executa("select * from Clientes ");
                    JOptionPane.showMessageDialog(null, "Registro inserido com sucesso");
                    try 
                    {
                        
                        con_base.resultset.first();
                        tf_Codigo.setText(con_base.resultset.getString("Código"));
                        tf_Autor.setText(con_base.resultset.getString("Autor"));
                        tf_Reu.setText(con_base.resultset.getString("Réu"));
                        tf_Forum.setText(con_base.resultset.getString("Fórum"));
                        tf_Acao.setText(con_base.resultset.getString("Ação"));
                        tf_Processo.setText(con_base.resultset.getString("Processo"));
                        tf_Telefone.setText(con_base.resultset.getString("Telefone"));
                        tf_Andamento.setText(con_base.resultset.getString("Andamento"));
                        tf_Audiencia.setText(con_base.resultset.getString("Audiencia"));
                        tf_Tarefas.setText(con_base.resultset.getString("Tarefas"));
                        tf_Vara.setText(con_base.resultset.getString("Vara"));
                        tf_matricula.setText(con_base.resultset.getString("matricula"));
                        tf_rg.setText(con_base.resultset.getString("rg"));
                        tf_cpf.setText(con_base.resultset.getString("cpf"));
                        tf_endereco.setText(con_base.resultset.getString("endereco"));
                        tf_dt_nac.setText(con_base.resultset.getString("data_nasc"));
                        tf_local_prisao.setText(con_base.resultset.getString("local_prisao"));
                        ckNovo.setSelected(con_base.resultset.getBoolean("novo"));
                    }
                    catch(SQLException erro)
                    {
                    JOptionPane.showConfirmDialog(null,"Não localizou dados " +erro);
                    }
                }
            } else {
                //Atualização no Banco de Dados
                String updateSQL = "Update Clientes SET "
                        + "Autor = '"+autor+"' ,"
                        + "Réu = '"+reu+"',"
                        + "Fórum = '"+forum+"',"
                        + "Ação = '"+acao+"',"
                        + "Vara = '"+vara+"',"
                        + "Processo = '"+processo+"',"
                        + "Telefone = '"+telefone+"',"
                        + "Andamento = '"+andamento+"',"
                        + "Audiencia ='"+audiencia+"', "
                        + "Tarefas = '"+tarefas+"',"
                        + "matricula = '"+matricula+"',"
                        + "data_nasc = '"+dt_nasc+"',"
                        + "rg = '"+rg+"',"
                        + "cpf = '"+cpf+"',"
                        + "endereco = '"+endereco+"',"
                        + "local_prisao = '"+local_prisao+"',"
                        + "novo = '"+novo+"'"
                        + " WHERE Código = '"+codigo+"';";
                

                con_base.statement.executeUpdate(updateSQL);
                con_base.executa("select * from Clientes ");
                JOptionPane.showMessageDialog(null,"Atualizado com sucesso!");
                try 
                {
                    con_base.resultset.first();
                    tf_Codigo.setText(con_base.resultset.getString("Código"));
                    tf_Autor.setText(con_base.resultset.getString("Autor"));
                    tf_Reu.setText(con_base.resultset.getString("Réu"));
                    tf_Forum.setText(con_base.resultset.getString("Fórum"));
                    tf_Acao.setText(con_base.resultset.getString("Ação"));
                    tf_Processo.setText(con_base.resultset.getString("Processo"));
                    tf_Telefone.setText(con_base.resultset.getString("Telefone"));
                    tf_Andamento.setText(con_base.resultset.getString("Andamento"));
                    tf_Audiencia.setText(con_base.resultset.getString("Audiencia"));
                    tf_Tarefas.setText(con_base.resultset.getString("Tarefas"));
                    tf_Vara.setText(con_base.resultset.getString("Vara"));
                    tf_matricula.setText(con_base.resultset.getString("matricula"));
                    tf_rg.setText(con_base.resultset.getString("rg"));
                    tf_cpf.setText(con_base.resultset.getString("cpf"));
                    tf_endereco.setText(con_base.resultset.getString("endereco"));
                    tf_dt_nac.setText(con_base.resultset.getString("data_nasc"));
                    tf_local_prisao.setText(con_base.resultset.getString("local_prisao"));
                    ckNovo.setSelected(con_base.resultset.getBoolean("novo"));
                }
                catch(SQLException erro)
                {
                JOptionPane.showMessageDialog(null,"Não localizou dados " +erro);
                }
            }
            
            
            
        }
        catch(SQLException erro)
        {
            JOptionPane.showConfirmDialog(null, "Não foi possível salvar"
                   + " dados " +erro);
        }
            
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        excluir();      
        
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        String parametro = tf_pesquisar.getText();
        String clausura = (String) comboPesquisa.getSelectedItem();
        String query = "";
        if ("Código".equals(clausura)) {
                query = "select * from Clientes where "+clausura+" = '"+parametro+ "'";  
        } else {
            query = "select * from Clientes where "+clausura+"  LIKE '%"+parametro+"%' ";
        }
        //Pesquisa no banco de dados        
        
        try 
        {
            boolean b = con_base.executa(query);
            con_base.resultset.first();
            tf_Codigo1.setText(con_base.resultset.getString("Código"));
            tf_Autor1.setText(con_base.resultset.getString("Autor"));
            tf_Reu1.setText(con_base.resultset.getString("Réu"));
            tf_Forum1.setText(con_base.resultset.getString("Fórum"));
            tf_Acao1.setText(con_base.resultset.getString("Ação"));
            tf_Processo1.setText(con_base.resultset.getString("Processo"));
            tf_Telefone1.setText(con_base.resultset.getString("Telefone"));
            tf_Andamento1.setText(con_base.resultset.getString("Andamento"));
            tf_Audiencia1.setText(con_base.resultset.getString("Audiencia"));
            tf_Tarefas1.setText(con_base.resultset.getString("Tarefas"));
            tf_Vara1.setText(con_base.resultset.getString("Vara"));
            tf_matricula1.setText(con_base.resultset.getString("matricula"));
            tf_rg1.setText(con_base.resultset.getString("rg"));
            tf_cpf1.setText(con_base.resultset.getString("cpf"));
            tf_endereco1.setText(con_base.resultset.getString("endereco"));
            tf_dt_nac1.setText(con_base.resultset.getString("data_nasc"));
            tf_local_prisao1.setText(con_base.resultset.getString("local_prisao"));
            ckNovo1.setSelected(con_base.resultset.getBoolean("novo"));
            if(!b){
                pesquisar.setVisible(true);
                pesquisar.setBounds(200, 200, 700, 600);
            }
            
        }
        catch(SQLException erro)
        {
            pesquisar.setVisible(false);
            JOptionPane.showMessageDialog(null,"Não localizou dados ");
        }
        
        
        
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_Salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Salvar1ActionPerformed
        // TODO add your handling code here:
       
        try
        {
            String codigo = tf_Codigo1.getText();
            String autor = tf_Autor1.getText();
            String reu = tf_Reu1.getText();
            String forum = tf_Forum1.getText();
            String acao = tf_Acao1.getText();
            String processo = tf_Processo1.getText();
            String telefone = tf_Telefone1.getText();
            String andamento = tf_Andamento1.getText();
            String audiencia = tf_Audiencia1.getText();
            String tarefas = tf_Tarefas1.getText();
            String vara = tf_Vara1.getText();
            String rg = tf_rg1.getText();
            String cpf = tf_cpf1.getText();
            String endereco = tf_endereco1.getText();
            String matricula = tf_matricula1.getText();
            String dt_nasc = tf_dt_nac1.getText();
            String local_prisao = tf_local_prisao1.getText();
            boolean novo = ckNovo1.isSelected();
             //Atualização no Banco de Dados
                String updateSQL = "Update Clientes SET "
                        + "Autor = '"+autor+"' ,"
                        + "Réu = '"+reu+"',"
                        + "Fórum = '"+forum+"',"
                        + "Ação = '"+acao+"',"
                        + "Vara = '"+vara+"',"
                        + "Processo = '"+processo+"',"
                        + "Telefone = '"+telefone+"',"
                        + "Andamento = '"+andamento+"',"
                        + "Audiencia ='"+audiencia+"', "
                        + "Tarefas = '"+tarefas+"',"
                        + "matricula = '"+matricula+"',"
                        + "data_nasc = '"+dt_nasc+"',"
                        + "rg = '"+rg+"',"
                        + "cpf = '"+cpf+"',"
                        + "endereco = '"+endereco+"',"
                        + "local_prisao = '"+local_prisao+"',"
                        + "novo = '"+novo+"'"
                        + " WHERE Código = '"+codigo+"';";
                

                con_base.statement.executeUpdate(updateSQL);
                con_base.executa("select * from Clientes ");
                try 
                {
                    con_base.resultset.first();
                    tf_Codigo1.setText(con_base.resultset.getString("Código"));
                    tf_Autor1.setText(con_base.resultset.getString("Autor"));
                    tf_Reu1.setText(con_base.resultset.getString("Réu"));
                    tf_Forum1.setText(con_base.resultset.getString("Fórum"));
                    tf_Acao1.setText(con_base.resultset.getString("Ação"));
                    tf_Processo1.setText(con_base.resultset.getString("Processo"));
                    tf_Telefone1.setText(con_base.resultset.getString("Telefone"));
                    tf_Andamento1.setText(con_base.resultset.getString("Andamento"));
                    tf_Audiencia1.setText(con_base.resultset.getString("Audiencia"));
                    tf_Tarefas1.setText(con_base.resultset.getString("Tarefas"));
                    tf_Vara1.setText(con_base.resultset.getString("Vara"));
                    tf_matricula1.setText(con_base.resultset.getString("matricula"));
                    tf_rg1.setText(con_base.resultset.getString("rg"));
                    tf_cpf1.setText(con_base.resultset.getString("cpf"));
                    tf_endereco1.setText(con_base.resultset.getString("endereco"));
                    tf_dt_nac1.setText(con_base.resultset.getString("data_nasc"));
                    tf_local_prisao1.setText(con_base.resultset.getString("local_prisao"));
                    ckNovo1.setSelected(con_base.resultset.getBoolean("novo"));
                    JOptionPane.showMessageDialog(null, "Salvo com sucesso");
                    pesquisar.setVisible(false);
                    mostrar_Dados();
                }
                catch(SQLException erro)
                {
                JOptionPane.showConfirmDialog(null,"Não localizou dados " +erro);
                }
        }
        catch(SQLException erro)
        {
            JOptionPane.showConfirmDialog(null, "Não foi possível salvar"
                    + " dados " +erro);
        }
        
    }//GEN-LAST:event_btn_Salvar1ActionPerformed

    
    private void btn_excluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir1ActionPerformed
        // TODO add your handling code here:    
        int decisao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o registro? ");
        // para sim = 0 || para nao = 1
        if (decisao  == 0) {
            String codigo = tf_Codigo1.getText();
            if (codigo == "0" || codigo.isEmpty()){
                JOptionPane.showMessageDialog(null, "Impossível excluir registro vazio");
            } else {
               int cod = Integer.parseInt(codigo);
               try
               {
                   //Exclusao SQL
                    String deletaSQL = "delete from Clientes where Código ='"+cod+"' ";
                    con_base.statement.executeUpdate(deletaSQL);
                    JOptionPane.showMessageDialog(null, "Excluido com Sucesso!");
                    con_base.executa("select * from Clientes ");
                    con_base.resultset.first();
                    mostrar_Dados();
                    pesquisar.setVisible(false);
               }
               catch(SQLException erro)
               {
                    JOptionPane.showMessageDialog(null, "Impossível excluir "+erro); 
               }
               
            }
            
        } 
    }//GEN-LAST:event_btn_excluir1ActionPerformed
    
    private void tf_Audiencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_Audiencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Audiencia1ActionPerformed

    private void tf_Acao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_Acao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Acao1ActionPerformed

    private void tf_Processo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_Processo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Processo1ActionPerformed

    private void tf_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_matriculaActionPerformed

    private void tf_local_prisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_local_prisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_local_prisaoActionPerformed

    private void comboPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPesquisaActionPerformed

    private void tf_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pesquisarActionPerformed

    private void ckNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckNovoActionPerformed

    private void tf_dt_nacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dt_nacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dt_nacActionPerformed

    private void tf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cpfActionPerformed

    private void tf_rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_rgActionPerformed

    private void tf_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_enderecoActionPerformed

    private void tf_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TelefoneActionPerformed

    private void tf_matricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_matricula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_matricula1ActionPerformed

    private void tf_endereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_endereco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_endereco1ActionPerformed

    private void tf_local_prisao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_local_prisao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_local_prisao1ActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        anterior2();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        // TODO add your handling code here:
        proximo2();
    }//GEN-LAST:event_btnProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btn_Anterior;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_Primeiro;
    private javax.swing.JButton btn_Proximo;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_Salvar1;
    private javax.swing.JButton btn_Ultimo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_excluir1;
    private javax.swing.JCheckBox ckNovo;
    private javax.swing.JCheckBox ckNovo1;
    private javax.swing.JComboBox comboPesquisa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lb_acao1;
    private javax.swing.JLabel lb_acao2;
    private javax.swing.JLabel lb_acao4;
    private javax.swing.JLabel lb_andamento1;
    private javax.swing.JLabel lb_audiencia1;
    private javax.swing.JLabel lb_audiencia2;
    private javax.swing.JLabel lb_audiencia3;
    private javax.swing.JLabel lb_audiencia4;
    private javax.swing.JLabel lb_autor;
    private javax.swing.JLabel lb_autor1;
    private javax.swing.JLabel lb_codigo;
    private javax.swing.JLabel lb_codigo1;
    private javax.swing.JLabel lb_contato;
    private javax.swing.JLabel lb_contato1;
    private javax.swing.JLabel lb_contato2;
    private javax.swing.JLabel lb_contato3;
    private javax.swing.JLabel lb_contato4;
    private javax.swing.JLabel lb_contato5;
    private javax.swing.JLabel lb_dt_nasc;
    private javax.swing.JLabel lb_endereco;
    private javax.swing.JLabel lb_endereco1;
    private javax.swing.JLabel lb_endereco2;
    private javax.swing.JLabel lb_endereco3;
    private javax.swing.JLabel lb_forum;
    private javax.swing.JLabel lb_forum1;
    private javax.swing.JLabel lb_loc_prisao;
    private javax.swing.JLabel lb_matricula;
    private javax.swing.JLabel lb_processo;
    private javax.swing.JLabel lb_processo1;
    private javax.swing.JLabel lb_reu;
    private javax.swing.JLabel lb_reu1;
    private javax.swing.JLabel lb_tarefas1;
    private javax.swing.JLabel lb_vara;
    private javax.swing.JLabel lb_vara1;
    private javax.swing.JMenu menuBase;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JFrame pesquisar;
    private javax.swing.JTextField tf_Acao;
    private javax.swing.JTextField tf_Acao1;
    private javax.swing.JTextArea tf_Andamento;
    private javax.swing.JTextArea tf_Andamento1;
    private javax.swing.JTextArea tf_Audiencia;
    private javax.swing.JTextField tf_Audiencia1;
    private javax.swing.JTextField tf_Autor;
    private javax.swing.JTextField tf_Autor1;
    private javax.swing.JTextField tf_Codigo;
    private javax.swing.JTextField tf_Codigo1;
    private javax.swing.JTextField tf_Forum;
    private javax.swing.JTextField tf_Forum1;
    private javax.swing.JTextField tf_Processo;
    private javax.swing.JTextField tf_Processo1;
    private javax.swing.JTextField tf_Reu;
    private javax.swing.JTextField tf_Reu1;
    private javax.swing.JTextArea tf_Tarefas;
    private javax.swing.JTextArea tf_Tarefas1;
    private javax.swing.JFormattedTextField tf_Telefone;
    private javax.swing.JFormattedTextField tf_Telefone1;
    private javax.swing.JTextField tf_Vara;
    private javax.swing.JTextField tf_Vara1;
    private javax.swing.JFormattedTextField tf_cpf;
    private javax.swing.JFormattedTextField tf_cpf1;
    private javax.swing.JFormattedTextField tf_dt_nac;
    private javax.swing.JFormattedTextField tf_dt_nac1;
    private javax.swing.JTextField tf_endereco;
    private javax.swing.JTextField tf_endereco1;
    private javax.swing.JTextField tf_local_prisao;
    private javax.swing.JTextField tf_local_prisao1;
    private javax.swing.JTextField tf_matricula;
    private javax.swing.JTextField tf_matricula1;
    private javax.swing.JTextField tf_pesquisar;
    private javax.swing.JFormattedTextField tf_rg;
    private javax.swing.JFormattedTextField tf_rg1;
    // End of variables declaration//GEN-END:variables

    public void mostrar_Dados() throws SQLException{

        int linhaAtual = con_base.resultset.getRow();
        if (linhaAtual != 0) {
            tf_dt_nac.setText("");
            tf_Telefone.setText("");
            tf_rg.setText("");
            tf_cpf.setText("");
        }    
        setFormatNumber("##/##/####", tf_dt_nac, "1234567890");
        setFormatNumber("(##) #####-####", tf_Telefone, "1234567890");
        setFormatNumber("##.###.###-#", tf_rg, "1234567890");
        setFormatNumber("###.###.###-##", tf_cpf, "1234567890");     


        try
        {
            tf_Codigo.setText(con_base.resultset.getString("Código"));
            tf_Autor.setText(con_base.resultset.getString("Autor"));
            tf_Reu.setText(con_base.resultset.getString("Réu"));
            tf_Forum.setText(con_base.resultset.getString("Fórum"));
            tf_Acao.setText(con_base.resultset.getString("Ação"));
            tf_Processo.setText(con_base.resultset.getString("Processo"));
            tf_Telefone.setText(con_base.resultset.getString("Telefone"));
            tf_Andamento.setText(con_base.resultset.getString("Andamento"));
            tf_Audiencia.setText(con_base.resultset.getString("Audiencia"));
            tf_Tarefas.setText(con_base.resultset.getString("Tarefas"));
            tf_Vara.setText(con_base.resultset.getString("Vara"));
            tf_matricula.setText(con_base.resultset.getString("matricula"));
            tf_rg.setText(con_base.resultset.getString("rg"));
            tf_cpf.setText(con_base.resultset.getString("cpf"));
            tf_endereco.setText(con_base.resultset.getString("endereco"));
            tf_dt_nac.setText(con_base.resultset.getString("data_nasc"));
            tf_local_prisao.setText(con_base.resultset.getString("local_prisao"));
            ckNovo.setSelected(con_base.resultset.getBoolean("novo"));

        }
        catch(SQLException erro)
        {
            if (navega == 1){
                JOptionPane.showMessageDialog(null, "Já esta no primeiro Registro");
            }else if (navega ==2){
                JOptionPane.showMessageDialog(null, "Já está no ultimo registro");
            }else 
                JOptionPane.showMessageDialog(null,"Não Localizou Dados:\n"+ erro);
            navega = 0;
        }

    }
    public void mostrar_DadosUm() throws SQLException{
    
    int linhaAtual = con_base.resultset.getRow();
    if (linhaAtual != 0) {
        tf_dt_nac1.setText("");
        tf_Telefone1.setText("");
        tf_rg1.setText("");
        tf_cpf1.setText("");
    }    
    setFormatNumber("##/##/####", tf_dt_nac1, "1234567890");
    setFormatNumber("(##) #####-####", tf_Telefone1, "1234567890");
    setFormatNumber("##.###.###-#", tf_rg1, "1234567890");
    setFormatNumber("###.###.###-##", tf_cpf1, "1234567890");     
        
    
    try
    {
        tf_Codigo1.setText(con_base.resultset.getString("Código"));
        tf_Autor1.setText(con_base.resultset.getString("Autor"));
        tf_Reu1.setText(con_base.resultset.getString("Réu"));
        tf_Forum1.setText(con_base.resultset.getString("Fórum"));
        tf_Acao1.setText(con_base.resultset.getString("Ação"));
        tf_Processo1.setText(con_base.resultset.getString("Processo"));
        tf_Telefone1.setText(con_base.resultset.getString("Telefone"));
        tf_Andamento1.setText(con_base.resultset.getString("Andamento"));
        tf_Audiencia1.setText(con_base.resultset.getString("Audiencia"));
        tf_Tarefas1.setText(con_base.resultset.getString("Tarefas"));
        tf_Vara1.setText(con_base.resultset.getString("Vara"));
        tf_matricula1.setText(con_base.resultset.getString("matricula"));
        tf_rg1.setText(con_base.resultset.getString("rg"));
        tf_cpf1.setText(con_base.resultset.getString("cpf"));
        tf_endereco1.setText(con_base.resultset.getString("endereco"));
        tf_dt_nac1.setText(con_base.resultset.getString("data_nasc"));
        tf_local_prisao1.setText(con_base.resultset.getString("local_prisao"));
        ckNovo1.setSelected(con_base.resultset.getBoolean("novo"));
        
    }
    catch(SQLException erro)
    {
        if (navega == 1){
            JOptionPane.showMessageDialog(null, "Já esta no primeiro Registro");
        }else if (navega ==2){
            JOptionPane.showMessageDialog(null, "Já está no ultimo registro");
        }else 
            JOptionPane.showMessageDialog(null,"Não Localizou Dados:\n"+ erro);
        navega = 0;
    }

}
public void limpar_Dados(){
    tf_Codigo.setText("");
    tf_Autor.setText("");
    tf_Reu.setText("");
    tf_Forum.setText("");
    tf_Acao.setText("");
    tf_Processo.setText("");
    tf_Telefone.setText("");
    tf_Andamento.setText("");
    tf_Audiencia.setText("");
    tf_Tarefas.setText("");
    tf_Vara.setText("");
    tf_matricula.setText("");
    tf_rg.setText("");
    tf_cpf.setText("");
    tf_endereco.setText("");
    tf_dt_nac.setText("");
    tf_local_prisao.setText("");
    ckNovo.setSelected(false);
}

    public void setFormatNumber(String maskFormat,
        JFormattedTextField jFormatedText, String validCar)
    {
        try{
            MaskFormatter mf = new MaskFormatter(maskFormat);
            mf.setValidCharacters(validCar);
            mf.setPlaceholderCharacter(' ');
            mf.install(jFormatedText); 
        } catch(ParseException pe){
            JOptionPane.showMessageDialog(null,
            "Erro na conversão dos dados no campo!" + pe,
            "Erro!",
            JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void proximo() {
        try
        {
            con_base.resultset.next();
            mostrar_Dados();
            navega = 2;
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível ir para "
                    + "o próximo registro. "+erro);
        }
    }
    public void proximo2() {
        try
        {
            con_base.resultset.next();
            mostrar_DadosUm();
            navega = 2;
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível ir para "
                    + "o próximo registro. "+erro);
        }
    }
    public void anterior() {
        try
        {
            con_base.resultset.previous();
            mostrar_Dados();
            navega = 1;
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível ir para"
                    + " o registro anterior. "+erro);
        }
    }
    public void anterior2() {
        try
        {
            con_base.resultset.previous();
            mostrar_DadosUm();
            navega = 1;
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível ir para"
                    + " o registro anterior. "+erro);
        }
    }
    public void excluir() {
        int decisao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o registro? ");
        // para sim = 0 || para nao = 1
        if (decisao  == 0) {
            String codigo = tf_Codigo.getText();
            if (codigo == "0" || codigo.isEmpty()){
                JOptionPane.showMessageDialog(null, "Impossível excluir registro vazio");
            } else {
               int cod = Integer.parseInt(codigo);
               try
               {
                   //Exclusao SQL
                    String deletaSQL = "delete from Clientes where Código ='"+cod+"' ";
                    con_base.statement.executeUpdate(deletaSQL);
                    JOptionPane.showMessageDialog(null, "Excluido com Sucesso!");
                    con_base.executa("select * from Clientes ");
                    con_base.resultset.first();
                    mostrar_Dados();
               }
               catch(SQLException erro)
               {
                    JOptionPane.showMessageDialog(null, "Impossível excluir "+erro); 
               }
               
            }
            
        }  
    }
    
}


